apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: date-task
      labels:
        app: myapp
    spec:
      containers:
        - name: date-task
          image: ornaishtat/date-task

